-- AlterTable
ALTER TABLE "Stream" ADD COLUMN     "Time" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Upvote" ADD COLUMN     "Time" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
